### ISSUE TITLE
Messages not being passed into Gitter from Matrix/Riot, but are still going Gitter => Matrix

### ISSUE THREAD

**Issue by jywarren** [matrix-org/matrix-appservice-gitter#72]
We're in https://riot.im/app/#/room/#publiclab:matrix.org and are linked to https://gitter.im/publiclab/publiclab with the built-in bridge available in the Riot interface. It's run for over a year (maybe 2 years?) but is no longer working. How can we troubleshoot this? 

Thanks!

**Comment by Half-Shot** [comment]
This has been resolved by the gitter folks.

**Comment by seldridge** [comment]
Apologies for resurrecting an old issue, but this appears to be happening again. Checking the two bridged rooms in the original issue show that the last matrix -> gitter traffic was on May 14, 2020. Everything since has been dropped. Gitter -> matrix traffic is still being relayed.

If it's more appropriate to open a new issue, I can. No other issues seem to be opened about this.

**Comment by Half-Shot** [comment]
I'll go ask gitter about it.

**Comment by seldridge** [comment]
Thanks for looking into this @Half-Shot. I checked just now and the Matrix -> Gitter bridge seems to be back to working.

**Comment by Half-Shot** [comment]
Awesome :)
